AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sends and slack message everytime a new file is stored in the S3 Bucket



# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 6

Resources:
  SendToSlackFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: SendToSlack/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
       HelloWorld:
         Type: S3 
         Properties:
           Bucket: !Ref testBucket
           Events: s3:ObjectCreated:*
      Policies:
        - S3ReadPolicy:
            BucketName: '*'

  testBucket:
    Type: AWS::S3::Bucket

